#source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
use_frameworks!

target 'Example' do
    pod 'Reed', :path => '~/myopensource/ios/Reed'
    pod 'CryptoSwift'

    pod 'ZKORM', :path => '~/myopensource/ios/ZKORM'
end
